import { TipoCompromisso } from '../store/useAgendaStore';

export type RootStackParamList = {
  Splash: undefined;
  Welcome: undefined;
  Storytelling: undefined;
  Login: undefined;
  Cadastro: undefined;
  RecuperarSenha: undefined;
  NovaSenha: undefined;
  CriarPerfil: undefined;
  AdicionarCavalo: { fromPerfis?: boolean } | undefined;
  Relacionamento: undefined;
  Preferencias: undefined;
  Permissoes: undefined;
  TourInteligente: undefined;
  PrimeiroCheckin: undefined;
  PrimeiraCartaIA: undefined;
  Home: undefined;
  NovoRegistro: { tipoInicial?: string } | undefined;
  MemoriaCompleta: { id?: string } | undefined;
  Timeline: undefined;
  Calendario: undefined;
  PesquisaMemorias: undefined;
  Favoritos: undefined;
  TipoMemoria: undefined;
  CapturaMidia: undefined;
  InformacoesRapidas: undefined;
  Descricao: undefined;
  Marcacao: undefined;
  Privacidade: undefined;
  Previa: undefined;
  MemoriaPublicada: { id?: string } | undefined;
  Historico: undefined;
  AlbunsInteligentes: undefined;
  Comparacao: undefined;
  Rascunhos: undefined;
  AlbumDetalhe: { nome: string; tipo?: string };
  Notificacoes: undefined;
  Comunidade: undefined;
  StoriesViewer: { startIndex?: number } | undefined;
  Reels: undefined;
  Explorar: undefined;
  Eventos: undefined;
  EventoDetalhe: { id: string };
  Grupos: undefined;
  GrupoDetalhe: { id: string };
  Mensagens: undefined;
  ChatConversa: { id: string };
  Comentarios: { postId: string };
  Perfis: undefined;
  EditarPerfil: undefined;
  PerfilPublico: undefined;
  Cavalos: undefined;
  PerfilCavalo: { id: string };
  TimelineCavalo: { id: string };
  SaudeCavalo: { id: string };
  HistoricoSaude: { id: string };
  Vacinas: { id: string };
  Vermifugacao: { id: string };
  Medicamentos: { id: string };
  Ferrageamento: { id: string };
  Odontologia: { id: string };
  Alimentacao: { id: string };
  Peso: { id: string };
  Exames: { id: string };
  Lesoes: { id: string };
  Recuperacao: { id: string };
  Veterinarios: { id: string };
  Documentos: { id: string };
  CalendarioSaude: { id: string };
  IABemEstar: { id: string };
  InteligenciaArtificial: undefined;
  CartasIA: undefined;
  LeituraCarta: { cartaId: string };
  Insights: undefined;
  LinhaTempoEmocional: undefined;
  Retrospectivas: undefined;
  HistoriasIA: undefined;
  Sugestoes: undefined;
  EstudioCriativo: undefined;
  AssistenteIA: undefined;
  EvolucaoCavalo: { id: string };
  GaleriaCavalo: { id: string };
  CartasCavalo: { id: string };
  CompartilharCavalo: { id: string };
  AgendaDashboard: undefined;
  AgendaCalendario: undefined;
  AgendaDoDia: { data?: string } | undefined;
  CriarCompromisso: { data?: string; tipoInicial?: TipoCompromisso } | undefined;
  PlanejamentoSemanal: undefined;
  Metas: undefined;
  Clima: undefined;
  Analytics: undefined;
  Evolucao: undefined;
  LinhaTempoAnalitica: undefined;
  InsightsInteligentes: undefined;
  Relatorios: undefined;
  EventosDescobrir: undefined;
  EventoPagina: { eventId: string };
  EventoInscricao: { eventId: string };
  EventosCalendario: undefined;
  Clubes: undefined;
  ComunidadesLocais: undefined;
  Experiencias: undefined;
  EventoCheckin: { eventId: string };
  AlbumColaborativo: { eventId: string };
  EventoNetworking: { eventId: string };
  EventoCertificado: { eventId: string };
  RankingEvento: { eventId: string };
  MeusEventos: undefined;
};

declare global {
  namespace ReactNavigation {
    interface RootParamList extends RootStackParamList {}
  }
}
